version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trade-finance-app
    container_name: trade-finance-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage  
      - ./vendor:/var/www/vendor    
    ports:
      - "9000:9000"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root  # root password for the root user
      MYSQL_DATABASE: trade_finance
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
